local dotman = require("dotman")
dotman = dotman:setup()
describe("config setup", function ()
	it("git_url", function ()
		assert.equals(nil, dotman.git_url)
	end)
	it("config_path", function ()
		assert.equals("/home/jake/.config", dotman.config_path)
	end)
	it("dotfile_path", function ()
		assert.equals( "/home/jake/.dotfiles", dotman.dotfile_path)
	end)
end)
